### PR TITLE
Type inference fix

### LINKED ISSUE #1586: Type inference fails with overloading, for variables and wildcards
I thought type inference was supposed to give variables the most general types that let a rule parse, and then assign other labels and terms the least sorts after that.
This doesn't seem to always work, and also I get different errors about variables and wildcards. Here's a sample definition, to be saved as `test.k`

```
require "domains.k"
module TEST-SYNTAX
syntax A ::= B | "a"
syntax B ::= "b"
syntax TA ::= TB | t(A) [klabel(t)]
syntax TB ::= t(B) [klabel(t)]
endmodule
module TEST
imports MAP
imports TEST-SYNTAX
configuration <k>$PGM:K</k>
rule t(X)::TA => .K
rule t(Y) => .K
rule t(_) => .K
endmodule
```

Compiling it produces as `kompile --kore test.k` produces this output:

```
[Error] Compiler: Had 1 parsing errors.
[Error] Critical: Could not infer a unique sort for variable 'Y'. Possible
sorts: A, B
    Source(/home/brandon/test/k/wildcard/././test.k)
    Location(13,6,13,16)
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax TB ::= "t" "(" B ")"
[Location(#token("6",Int),#token("15",Int),#token("6",Int),#token("30",Int))
Source(#token("/home/brandon/test/k/wildcard/././test.k",KString))
klabel(#token("t",AttributeValue)) klabel(#token("t",KString))]
    t(#SemanticCastToB(#token(#KVariable,"_")))
2: syntax TA ::= "t" "(" A ")"
[Location(#token("5",Int),#token("20",Int),#token("5",Int),#token("35",Int))
Source(#token("/home/brandon/test/k/wildcard/././test.k",KString))
klabel(#token("t",AttributeValue)) klabel(#token("t",KString))]
    t(#SemanticCastToA(#token(#KVariable,"_")))
    Source(/home/brandon/test/k/wildcard/././test.k)
    Location(12,6,12,10)
```

Note that there's an error about `Y` but not `X` even though `Y` could be typed just like `X`, and that the wildcard gets only a warning even though the ambiguity is equivalent to the ambiguity about `Y` (and it just happens to default to the less general type).

I expected all of X, Y, and _ to end up having inferred type A.

### PR DESCRIPTION
**Pull request by bmmoore**
This updates the type inference code to calculate sorts also for _ variables, and to more carefully combine sort constraints from multiple possible parses.

Now a variable is assigned an inferred sort only if that sort is a (nonstrict) supersort of the sort the variable has in every possible way of assigning legal variable sorts in any of the possible ambiguous parses. An error will be reported if any variable doesn't have a unique maximal sort, or if it's not possible to simultaneously assign all those sorts. Also, an ambiguity error will be reported a bit after this code if assigning these inferred types isn't enough to reduce the possible parses down to a single KORE term (debugging VariableTypeInferenceFilter may show some ambiguity nodes, because this code is still working in terms of productions where e.g. overloaded labels may lead to mutliple syntax trees that still eventually flatten to the same AST).

@radumereuta please review.

Fixes #1586 and #1603.

### CODE REVIEW

**Comment by bmmoore** [comment]
Passes when I run that test by hand, or run ktest locally.

**Comment by bmmoore** [comment]
Jenkins: retest this please

**Comment by dwightguth** [comment]
lgtm. When you parse the C semantics with this are you able to successfully run tests in the OCAML backend?

**Comment by bmmoore** [comment]
C is actually broken in master, from a bug filed as #1612. I'm looking into it, I suspect it was a missed problem in the cell fragments change.

**Comment by bmmoore** [comment]
That's been fixed now. Just to match what I'm testing C against on my local machine, I'm retesting this branch.

**Comment by bmmoore** [comment]
Jenkins: retest this please.

**Comment by bmmoore** [comment]
@dwightguth The `test-build` target passed. (I had to fix the C makefile to not lose K's increased stack size when setting K_OPTS to avoid a stack overflow).

File: kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java [hunk 1]
```diff
@@ -58,6 +61,111 @@ public VariableTypeInferenceFilter(POSet<Sort> subsorts, scala.collection.immuta
...
+
+        nextsort:
+        for (Sort vv1 : sorts) {
+            for (Sort vv2 : sorts)
+                if (subsorts.lessThan(vv1, vv2))
+                    continue nextsort;
+            maxSorts.add(vv1);
+        }
+        return maxSorts;
+    }
```
Comment (radumereuta) [inline kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java]: Wait, how does this work? Continue goes back to the beginning... What is the exit condition?
Also, are jumps allowed?
I usually implemented maximal like this:

```
for (Sort vv1 : sorts) {
    boolean maximal = true;
    for (Sort vv2 : sorts) {
        if (subsorts.lessThan(vv1, vv2)) {
            maximal = false;
            break;
        }
        if (maximal)
            maxSorts.add(vv1);
    }
}
```

File: kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java [hunk 2]
```diff
@@ -58,6 +61,111 @@ public VariableTypeInferenceFilter(POSet<Sort> subsorts, scala.collection.immuta
...
+        for (Sort sort : iterable(sortSet)) { // for every declared sort
+            if (subsorts.lessThanEq(sort, Sort("KBott")))
+                continue;
+            for (Sort bound : bounds)
+                if (!subsorts.greaterThanEq(bound, sort))
+                    continue nextsort;
+            mins.add(sort);
+        }
+        return mins;
+    }
```
Comment (radumereuta) [inline kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java:79]: Shouldn't these be part of `POSet`?
They feel like general operations over a poset. I think in KIL we had them implemented like that, but in KORE we haven't ported all the operations. Also, the ones we have right now are implemented really inefficiently.
And again, I don't understand how this one finishes if you implement it like this with jumps.

File: kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java [hunk 3]
```diff
@@ -95,55 +203,20 @@ public VariableTypeInferenceFilter(POSet<Sort> subsorts, scala.collection.immuta
...
-                            solution.putAll(key, maxSorts);
-                        else {
-                            failsAmb = maxSorts;
-                            failsAmbName = key;
-                            solution.clear();
-                            break;
-                        }
                     } else {
-                        solution.putAll(key, mins);
+                        solution.putAll(key, maximal(mins));
```
Comment (radumereuta) [inline kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java]: Ah, ok. I get why you put the code in this file.

File: kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java [hunk 4]
```diff
@@ -347,4 +347,36 @@ public void test20() {
...
+                "module TEST\n" +
+                "syntax T ::= \"wrap\" M [klabel(wrapM)] | \"wrap\" X [klabel(wrapX)]\n" +
+                "syntax A\n" +
+                "syntax B\n" +
+                "syntax M ::= A | B\n" +
+                "syntax N ::= A | B | X // make A and B both maximal in the intersection of N and M\n" +
+                "syntax X\n" +
+                "syntax KItem ::= label(N,T)\n" +
+                "endmodule";
+        parseRule("X => label(X,wrap X)", def, 0, true);
```
Comment (radumereuta) [inline kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java:380]: This should have a warning. X is not declared so it should contain a hidden warning.

File: kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java (hunk 1 above)
Comment (bmmoore) [inline kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java]: It's continuing the outer loop. It's a named loop, not a jump label: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/branch.html

File: kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java (hunk 2 above)
Comment (bmmoore) [inline kernel/src/main/java/org/kframework/parser/concrete2kore/disambiguation/VariableTypeInferenceFilter.java:79]: Maybe it should. This code used to be in the body of the apply method, and I only took it as far as extracting it into a method - also the new POSet is written in scala so I couldn't just refactor the method to there.

File: kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java (hunk 4 above)
Comment (bmmoore) [inline kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java:380]: I'm expecting an error (with `true`) rather than assign X a sort, as discussed at #1603. Making type inference behave that way is one of the points of making this pull request.

**Comment by bmmoore** [comment]
FYI, @cos maybe you want to look at the POSet method?

**Comment by radumereuta** [comment]
I just tested the issue myself. If this is the wanted behavior, then go ahead with merging.
lgtm
